### PR TITLE
Fix bool parse bug

### PR DESCRIPTION
**Pull request by LiamWalsh98**
Change the order of attempted observation to avoid ambiguity.

For details, see discussion in #11

### CODE REVIEW

**Comment by LiamWalsh98** [comment]
Looks like there are quite a few more tests in `internal/` that are failing now. I will have to check on these later. Unless you can in the meantime @twpayne

**Comment by twpayne** [comment]
It's sufficient to replace the `*.gen.go` files in `internal/tests/` with the new versions.

**Comment by twpayne** [comment]
You can use the `*.gen.go.actual` files (generated by the tests, but `.gitignore`d) to directly replace the `*.gen.go` files.

**Comment by LiamWalsh98** [comment]
Ahh, gotcha. Will do, thanks

**Comment by twpayne** [comment]
Perfect! Thank you for this excellent contribution and your thoroughness and patience in the contribution process!

**Comment by twpayne** [comment]
I've tagged [`v1.1.0`](https://github.com/twpayne/go-xmlstruct/releases/tag/v1.1.0) with the changes.

**Comment by LiamWalsh98** [comment]
Awesome, thanks so much for the help and responsiveness!

**Pull request merged**
