### PR TITLE
feat: add WithImports option

### LINKED ISSUE #31: Exclude import statements when package name is empty
I am using goxmlstruct to generate structs to be included in existing source code files, so I am running it with `goxmlstruct -package-name="" -header=""` to exclude the file level decelerations.

However, when using the `-named-root` option, or when the xml includes a time value, an import statement is added to the output to include `encoding/xml` and/or  `time`.

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #31.

@meblum does this look reasonable? You'll need to set the `WithImports(false)` option in your code.

### CODE REVIEW

**Comment by meblum** [comment]
Wow, you're quick :) From a usability perspective, instead of  `WithImports(false)`, perhaps there should be single option that does the equivalent of  `WithImports(false) WithHeader("") WithPackageName("")` ? I don't see the use case of someone setting WithImports(false) but still want a package declaration.

**Comment by meblum** [comment]
I mean, for the library, that's not a big deal it can stay the way it is, but for the cli it should probably be combined as a single option.

**Comment by twpayne** [comment]
Good idea. Something like `-types-only` as in 36cb37aa03b5381fb4fd43e0f45945309525e277?

**Comment by meblum** [comment]
Yes! Thanks so much!!!

**Comment by twpayne** [comment]
OK, done. Tagged `v1.6.0` with these extra options and flags. Thank you very much for your work here!

**Pull request merged**
